- name: this playbook  for apache2 installation
  hosts: all
  tasks:
    - name: install apache2
      apt:
          name: apache2
          state: latest

    -  name: install httpd
       yum: 
         name: httpd
         state: latest       