- name: update webserver
  hosts: all
  become: true

  tasks:
    - name: change web page
      copy:
        src: index.html
        dest: /var/www/html/index.html
    
    - name: add online
      lineinfile: 
        path: /var/www/html/index.html
        regexp: '</h1>'
        line: '<h1> hello there this cloud </h1>'

    - name: add block of lines
      blockinfile:
        path: /var/www/html/index.html
        block: |
           this is batch23
           welcome all for devops

    - name: start service
      systemd:
        name: apache2
        state: restarted
        enabled: true