- name: update webserver
  hosts: all
  become: true

  tasks:
    - name: change web page
      copy:
        src: index.html
        dest: /var/www/html/index.html
    
    - name: add online
      lineinfile: 
        path: /var/www/html/index.html
        regexp: '</h1>'
        line: '<h1> hello there this cloud </h1>'

    - name: add block of lines
      blockinfile:
        path: /var/www/html/index.html
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        block: |
          <h1> hello my name is yogita </h1>
          <h2> this is batch23 </h2>
          <h3> welcome all for devops </h3>


    - name: start service
      systemd:
        name: apache2
        state: restarted
        enabled: true