- name: this is variable learning
  hosts: all
 # vars:
  #  animal: "Tiger"
  #vars_files:
   # - ./var.txt
  vars_prompt:
    - name: animal
      prompt: "Enter the name of the animal"
      
  tasks:
    - name: print animal 1
      debug:
        msg: "{{ animal }}"
    - name: print animal 2
      debug:
        msg: "{{ animal }}"
    - name: print animal 3
      debug:
        msg: "{{ animal }}"
        vars:
          animal: "Lion"
