apiVersion: v1
kind: Pod
metadata:
  name: my1stapp
  labels:
    app: my1stapp
spec:
  containers:
  - name: my1stapp
    image: yogitadeshmukh/batch23:httpd-v1

    resources:
      
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
