apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myreplicaset
  

spec:
  replicas: 5
  selector:
    matchLabels:
      app: mynginx
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
  template:
    metadata:
      labels:
        env: dev
        app: mynginx
    spec:
      containers:
      - name: myreplicaset
        image: nginx
        ports:
        - containerPort: 80
        